start cmd /c "rosbag play D:\jaron_ws\MCRING\soft_sync\imu\IMUbag\IMU_0.bag"
start cmd /c "rosbag play D:\jaron_ws\MCRING\soft_sync\imu\IMUbag\IMU_1.bag"
start cmd /c "rosbag play D:\jaron_ws\MCRING\soft_sync\imu\IMUbag\IMU_2.bag"
start cmd /c "rosbag play D:\jaron_ws\MCRING\soft_sync\imu\IMUbag\IMU_3.bag"
start cmd /c "rosbag play D:\jaron_ws\MCRING\soft_sync\imu\IMUbag\IMU_4.bag"
